MyApp Class Reference
#include MyApp.h
Public Member Functions
MyApp ()
virtual ~MyApp ()
virtual void Run ()
virtual JSValue GetFile (const JSObject &thisObject, const JSArgs &args)
virtual void OnUpdate () override
virtual void OnClose (ultralight::Window *window) override
virtual void OnResize (ultralight::Window *window, uint32_t width, uint32_t height) override
virtual void OnFinishLoading (ultralight::View *caller, uint64_t frame_id, bool is_main_frame, const String &url) override
virtual void OnDOMReady (ultralight::View *caller, uint64_t frame_id, bool is_main_frame, const String &url) override
virtual void OnChangeCursor (ultralight::View *caller, Cursor cursor) override
virtual void OnChangeTitle (ultralight::View *caller, const String &title) override
Protected Attributes
RefPtr< App > app_
RefPtr< Window > window_
RefPtr< Overlay > overlay_
Constructor & Destructor Documentation
MyApp()
MyApp::MyApp ()
Create our main App instance.
Create a resizable window by passing by OR'ing our window flags with kWindowFlags_Resizable.
Create our HTML overlay-- we don't care about its initial size and position because it'll be calculated when we call OnResize() below.
Force a call to OnResize to perform size/layout of our overlay.
Load a page into our overlay's View
Register our MyApp instance as an AppListener so we can handle the App's OnUpdate event below.
Register our MyApp instance as a WindowListener so we can handle the Window's OnResize event below.
Register our MyApp instance as a LoadListener so we can handle the View's OnFinishLoading and OnDOMReady events below.
Register our MyApp instance as a ViewListener so we can handle the View's OnChangeCursor and OnChangeTitle events below.
References app_, OnResize(), overlay_, window_, WINDOW_HEIGHT, and WINDOW_WIDTH.
~MyApp()
MyApp::~MyApp () [virtual]
Member Function Documentation
GetFile()
JSValue MyApp::GetFile (const JSObject & thisObject, const JSArgs & args) [virtual]
References BUFSIZE, and window_.
Referenced by OnDOMReady().
OnChangeCursor()
void MyApp::OnChangeCursor (ultralight::View * caller, Cursor cursor) [override], [virtual]
This is called whenever the page requests to change the cursor.
We update the main window's cursor here.
References window_.
OnChangeTitle()
void MyApp::OnChangeTitle (ultralight::View * caller, const String & title) [override], [virtual]
This is called whenever the page requests to change the title.
We update the main window's title here.
References window_.
OnClose()
void MyApp::OnClose (ultralight::Window * window) [override], [virtual]
References app_.
OnDOMReady()
void MyApp::OnDOMReady (ultralight::View * caller, uint64_t frame_id, bool is_main_frame, const String & url) [override], [virtual]
This is called when a frame's DOM has finished loading on the page.
This is the best time to setup any JavaScript bindings.
References GetFile().
OnFinishLoading()
void MyApp::OnFinishLoading (ultralight::View * caller, uint64_t frame_id, bool is_main_frame, const String & url) [override], [virtual]
This is called when a frame finishes loading on the page.
OnResize()
void MyApp::OnResize (ultralight::Window * window, uint32_t width, uint32_t height) [override], [virtual]
This is called whenever the window changes size (values in pixels).
We resize our overlay here to take up the entire window.
References overlay_.
Referenced by MyApp().
OnUpdate()
void MyApp::OnUpdate () [override], [virtual]
This is called repeatedly from the application's update loop.
You should update any app logic here.
Run()
void MyApp::Run () [virtual]
References app_.
Referenced by main().
Member Data Documentation
app_
RefPtr<App> MyApp::app_ [protected]
Referenced by MyApp(), OnClose(), and Run().
overlay_
RefPtr<Overlay> MyApp::overlay_ [protected]
Referenced by MyApp(), and OnResize().
window_
RefPtr<Window> MyApp::window_ [protected]
Referenced by GetFile(), MyApp(), OnChangeCursor(), and OnChangeTitle().
The documentation for this class was generated from the following files:
src/GUI/MyApp.h
src/GUI/MyApp.cpp