name: CMake Windows with Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build

      - name: Build
        run: cmake --build ${{github.workspace}}\build 

      - name: Move executables
        run: |
         Move-Item "${{github.workspace}}\build\x64\Debug\*" "${{github.workspace}}\build"
        shell: powershell

      - name: Install and Run OpenCppCoverage
        run: |
          choco install opencppcoverage
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Generate Report
        working-directory: ${{github.workspace}}\build\
        id: generate_test_report
        shell: cmd
        run: |
           OpenCppCoverage.exe --excluded_sources ${{github.workspace}}\lib --export_type cobertura:${{github.workspace}}\build\Diglot.xml -- "${{github.workspace}}\build\tests" 

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          working-directory: ${{github.workspace}}\build\
          files: .\build\Diglot.xml
          fail_ci_if_error: true
          functionalities: fix
