name: CMake Windows with Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

      - name: Move executables
        run: |
         Move-Item "${{github.workspace}}\build\Debug\*" "${{github.workspace}}\build"
         dir ${{github.workspace}}\build
        shell: powershell

      - name: Install and Run OpenCppCoverage
        run: |
          dir ${{github.workspace}}\build\

          choco install opencppcoverage
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Generate Report
        id: generate_test_report
        shell: cmd
        run: OpenCppCoverage.exe --excluded_sources ${{github.workspace}}\lib --export_type cobertura:Diglot.xml -- "${{github.workspace}}\build\tests" 

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: .\Diglot.xml
          fail_ci_if_error: true
          functionalities: fix
